const CONFIG = {
  name: "Rahul",
  title: "Full-Stack Developer",
  roles: [
    "Full Stack Developer",
    "Mobile Application Developer",
    "Problem Solver",
  ],
  email: "rahul@example.com",
  phone: "+1 (555) 123-4567",
  location: "San Francisco, CA",
  github: "Rahul-NB-1806",
  linkedin: "rahul-n-b-308763411",
  resumeUrl: "./public/resume.pdf",
  social: {
    github: "https://github.com/Rahul-NB-1806",
    linkedin: "https://www.linkedin.com/in/rahul-n-b-308763411",
    twitter: "https://twitter.com/Rahul-NB-1806",
  },
  skills: [
    { name: "Java", icon: "☕", category: "Languages" },
    { name: "Python", icon: "🐍", category: "Languages" },
    { name: "JavaScript", icon: "⚡", category: "Languages" },
    { name: "TypeScript", icon: "📘", category: "Languages" },
    { name: "HTML", icon: "🌐", category: "Languages" },
    { name: "CSS", icon: "🎨", category: "Languages" },
    { name: "React", icon: "⚛️", category: "Frontend" },
    { name: "React Native", icon: "📱", category: "Mobile" },
    { name: "Tailwind CSS", icon: "💨", category: "Frontend" },
    { name: "Bootstrap", icon: "🅱️", category: "Frontend" },
    { name: "Framer Motion", icon: "🎬", category: "Frontend" },
    { name: "Node.js", icon: "🟢", category: "Backend" },
    { name: "Express.js", icon: "🚀", category: "Backend" },
    { name: "REST API", icon: "🔗", category: "Backend" },
    { name: "JWT", icon: "🔑", category: "Backend" },
    { name: "MongoDB", icon: "🍃", category: "Databases" },
    { name: "MySQL", icon: "🐬", category: "Databases" },
    { name: "Firebase", icon: "🔥", category: "Databases" },
    { name: "Android Studio", icon: "🤖", category: "Mobile" },
    { name: "Git", icon: "🔀", category: "Tools" },
    { name: "GitHub", icon: "🐙", category: "Tools" },
    { name: "VS Code", icon: "💻", category: "Tools" },
  ],
  projects: [
    {
      title: "Voice Assistant Mobile App",
      description:
        "AI-powered voice assistant with natural language processing and smart home integration.",
      tech: ["React Native", "Node.js", "Firebase"],
      image: null,
      github: "#",
      live: "#",
      features: [
        "Voice recognition and NLP processing",
        "Smart home device control",
        "Real-time voice-to-text conversion",
        "Multi-language support",
      ],
      challenges: [
        "Optimizing real-time audio processing on mobile",
        "Reducing latency for voice commands",
      ],
    },
    {
      title: "BOI Monitor Mobile Application",
      description:
        "Real-time monitoring app for bank transaction alerts and account activity tracking.",
      tech: ["React Native", "Express.js", "MongoDB"],
      image: null,
      github: "#",
      live: "#",
      features: [
        "Real-time push notifications for transactions",
        "Transaction history with filtering",
        "Multi-account support",
        "Security alerts and fraud detection",
      ],
      challenges: [
        "Handling real-time WebSocket data streams",
        "Bank-level security compliance",
      ],
    },
    {
      title: "Smart Parking Management System",
      description:
        "IoT-enabled smart parking solution with real-time slot detection and reservation system.",
      tech: ["Node.js", "MongoDB", "IoT"],
      image: null,
      github: "#",
      live: "#",
      features: [
        "Real-time parking slot availability",
        "Mobile reservation and payment",
        "IoT sensor integration",
        "Analytics dashboard",
      ],
      challenges: [
        "IoT sensor calibration and data accuracy",
        "Handling concurrent booking conflicts",
      ],
    },
    {
      title: "Plant E-Commerce Platform",
      description:
        "Full-stack plant marketplace with AI care recommendations and delivery tracking.",
      tech: ["React", "Node.js", "MongoDB"],
      image: null,
      github: "#",
      live: "#",
      features: [
        "Product catalog with plant care guides",
        "AI-powered plant recommendation engine",
        "Order tracking and delivery updates",
        "Community garden forum",
      ],
      challenges: [
        "Building accurate recommendation algorithm",
        "Real-time inventory management",
      ],
    },
    {
      title: "BikerZone",
      description:
        "Social platform for motorcycle enthusiasts with route planning and community features.",
      tech: ["React Native", "Express.js", "Firebase"],
      image: null,
      github: "#",
      live: "#",
      features: [
        "Interactive route planning with GPX export",
        "Community events and meetups",
        "Real-time location sharing",
        "Garage management for bikes",
      ],
      challenges: [
        "Offline-first map support",
        "Real-time location with battery optimization",
      ],
    },
  ],
  aboutMe: `I'm a full-stack developer who loves building products that live at the intersection of thoughtful design and solid engineering. I specialize in creating mobile and web applications that feel intuitive, performant, and polished — from the API layer all the way to the pixel-perfect UI. When I'm not coding, you'll find me exploring new tools, contributing to open source, or planning my next road trip.`,
  experience: [
    {
      company: "TechCorp Inc.",
      role: "Senior Full-Stack Developer",
      period: "2023 - Present",
      highlights: [
        "Led migration from monolith to microservices, improving deployment frequency by 5x",
        "Mentored team of 8 developers across 3 squads",
        "Reduced infrastructure costs by 35% through optimization",
        "Architected real-time data pipeline processing 1M+ events/day",
      ],
    },
    {
      company: "StartupXYZ",
      role: "Full-Stack Developer",
      period: "2021 - 2023",
      highlights: [
        "Developed MVP to production in 3 months, securing $2M seed funding",
        "Implemented CI/CD pipeline reducing release cycle from 2 weeks to daily",
        "Built real-time collaboration features using WebSockets",
      ],
    },
    {
      company: "WebAgency Co.",
      role: "Junior Developer",
      period: "2019 - 2021",
      highlights: [
        "Delivered 20+ client projects on time and within budget",
        "Developed reusable component library used across all projects",
        "Introduced automated testing improving code coverage to 85%",
      ],
    },
  ],
  education: [
    {
      institution: "University of California",
      degree: "B.S. Computer Science",
      period: "2015 - 2019",
      gpa: "3.8",
      highlights: ["Dean's List", "ACM Programming Contest finalist"],
    },
  ],
  certifications: [
    { name: "AWS Solutions Architect", issuer: "Amazon", year: "2023" },
    { name: "Google Cloud Professional", issuer: "Google", year: "2022" },
    { name: "Meta Front-End Developer", issuer: "Meta", year: "2022" },
    { name: "MongoDB Associate Developer", issuer: "MongoDB", year: "2023" },
  ],
};
