const CONFIG = {
  name: "Rahul",
  title: "Full-Stack Developer",
  roles: [
    "Full Stack Developer",
    "Mobile Application Developer",
    "Problem Solver",
  ],
  email: "rahulnb1806@gmail.com",
  phone: "+91 9092932937",
  location: "Coimbatore, India",
  github: "Rahul-NB-1806",
  linkedin: "rahul-n-b-308763411",
  resumeUrl: "/resume.pdf",
  social: {
    github: "https://github.com/Rahul-NB-1806",
    linkedin: "https://www.linkedin.com/in/rahul-n-b-308763411",
    twitter: "https://twitter.com/Rahul-NB-1806",
  },
  skills: [
    { name: "HTML", icon: "🌐", category: "Frontend" },
    { name: "CSS", icon: "🎨", category: "Frontend" },
    { name: "JavaScript", icon: "⚡", category: "Languages" },
    { name: "React", icon: "⚛️", category: "Frontend" },
    { name: "Java", icon: "☕", category: "Languages" },
    { name: "Python", icon: "🐍", category: "Languages" },
    { name: "Git", icon: "🔀", category: "Tools" },
    { name: "GitHub", icon: "🐙", category: "Tools" },
    { name: "VS Code", icon: "💻", category: "Tools" },
  ],
  projects: [
    {
      title: "Green-Cart",
      description: "E-commerce platform for eco-friendly products built with React.",
      tech: ["React", "JavaScript", "CSS"],
      image: null,
      github: "https://github.com/Rahul-NB-1806/Green-Cart",
      live: "https://green-cart-orpin-eta.vercel.app",
      features: ["Product browsing and search", "Shopping cart management", "Responsive modern UI", "Vercel deployment"],
      challenges: ["Building a clean and responsive interface", "State management across components"],
    },
    {
      title: "BOI Monitor",
      description: "Bank of India monitoring system built with Java for transaction tracking.",
      tech: ["Java", "Swing"],
      image: null,
      github: "https://github.com/Rahul-NB-1806/BOI-MONITOR",
      live: "#",
      features: ["Transaction monitoring", "User-friendly desktop interface", "Data organization"],
      challenges: ["Java Swing UI design", "Data management in desktop app"],
    },
    {
      title: "SLOT-GUARD",
      description: "Smart parking management system for real-time parking slot monitoring.",
      tech: ["HTML", "CSS", "JavaScript"],
      image: null,
      github: "https://github.com/Rahul-NB-1806/SLOT-GUARD",
      live: "#",
      features: ["Parking slot availability display", "Real-time slot monitoring", "Interactive UI"],
      challenges: ["Designing intuitive parking UI", "Real-time data handling"],
    },
    {
      title: "BIKER-ZONE",
      description: "E-commerce platform for motorcycle accessories built with React.",
      tech: ["React", "JavaScript", "CSS"],
      image: null,
      github: "https://github.com/Rahul-NB-1806/BIKER-ZONE",
      live: "#",
      features: ["Product catalog for bike accessories", "Shopping cart system", "Responsive design"],
      challenges: ["Building product filtering", "React component architecture"],
    },
    {
      title: "Voice Assistant",
      description: "Voice assistant application built with Java for voice-enabled tasks.",
      tech: ["Java"],
      image: null,
      github: "https://github.com/Rahul-NB-1806/Voice-Assistant",
      live: "#",
      features: ["Voice command recognition", "Task automation", "Desktop voice interface"],
      challenges: ["Voice processing in Java", "Command parsing logic"],
    },
    {
      title: "TRAFFIC ANALYSIS",
      description: "Traffic analysis system for vehicle movement patterns and congestion trends using Python.",
      tech: ["Python"],
      image: null,
      github: "https://github.com/Rahul-NB-1806/TRAFFIC-ANALYSIS",
      live: "#",
      features: ["Traffic data processing", "Congestion pattern analysis", "Data visualization"],
      challenges: ["Data processing efficiency", "Pattern recognition algorithms"],
    },
  ],
  aboutMe: `I'm a passionate frontend developer committed to refining my CSS, HTML, and React skills. My relentless dedication drives me to continually learn and adapt, staying at the forefront of web development trends. My goal is to create captivating, responsive, and user-friendly web interfaces that deliver exceptional user experiences.`,
  experience: [
    {
      company: "Self-Employed / Freelance",
      role: "Frontend Developer",
      period: "2024 - Present",
      highlights: [
        "Building responsive web interfaces using HTML, CSS, JavaScript, and React",
        "Developing multiple portfolio projects including e-commerce platforms",
        "Learning and implementing modern web development practices",
      ],
    },
  ],
  education: [
    {
      institution: "Coimbatore Institute of Technology",
      degree: "B.E. Computer Science",
      period: "2023 - 2027",
      gpa: "7.19",
      highlights: ["Focus on full-stack web development"],
    },
    {
      institution: "Vidyaa Vikas Matric Higher Secondary School",
      degree: "Higher Secondary (Matric)",
      period: "2020 - 2023",
      highlights: ["Percentage: 69.3%"],
    },
  ],
  certifications: [
    { name: "Frontend Development", issuer: "Self-Learning", year: "2025" },
    { name: "Succeeding in Web Development: Full Stack and Front End", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Create an Open-Source Project in Python", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Practical GitHub Project Management and Collaboration", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Git Workflows", issuer: "LinkedIn Learning", year: "2025" },
    { name: "iOS 17 Development Essential Training", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Building Your First iOS 17 App", issuer: "LinkedIn Learning", year: "2025" },
    { name: "HTML, CSS, and JavaScript: Building the Web", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Learning REST APIs", issuer: "LinkedIn Learning", year: "2025" },
    { name: "React Native Ecosystem and Workflow", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Web Development Tools: Enhance Workflow and Code Quality", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Learn JavaScript: Write Modern Code with JavaScript ESNext", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Software Design: Modeling with UML", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Getting Your Website Online", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Introduction to Web Design and Development", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Create a CRM Mobile Application with React Native", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Introduction to Dart", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Introduction to Web APIs", issuer: "LinkedIn Learning", year: "2025" },
    { name: "HTTP Essential Training", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Learning GitHub", issuer: "LinkedIn Learning", year: "2025" },
    { name: "MongoDB Essential Training", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Next.js: Creating and Hosting a Full-Stack Site", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Android Studio Essential Training", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Building Modern Projects with React", issuer: "LinkedIn Learning", year: "2025" },
    { name: "HTML Essential Training", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Building AI-Powered Android Apps with Gemini", issuer: "LinkedIn Learning", year: "2025" },
    { name: "How to Plan Your Website", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Create a Quick, Clean, and Cheap Website with Bootstrap Templates", issuer: "LinkedIn Learning", year: "2025" },
    { name: "Learning Responsive Media", issuer: "LinkedIn Learning", year: "2025" },
  ],
};

export default CONFIG;
